insert into kota (idKota, namaKota, negara, kodePos) values (1, 'Xinshan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (2, 'Heling', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (3, 'Shirgjan', 'Albania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (4, 'Los Santos', 'Colombia', '684009');
insert into kota (idKota, namaKota, negara, kodePos) values (5, 'Matahuasi', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (6, 'Yŏng-dong', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (7, 'Honiara', 'Solomon Islands', null);
insert into kota (idKota, namaKota, negara, kodePos) values (8, 'Koysinceq', 'Iraq', null);
insert into kota (idKota, namaKota, negara, kodePos) values (9, 'Jiushe', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (10, 'Kufa', 'Iraq', null);
insert into kota (idKota, namaKota, negara, kodePos) values (11, 'Brusartsi', 'Bulgaria', '3921');
insert into kota (idKota, namaKota, negara, kodePos) values (12, 'Nakhon Nayok', 'Thailand', '26120');
insert into kota (idKota, namaKota, negara, kodePos) values (13, 'Sentieiras', 'Portugal', '2200-499');
insert into kota (idKota, namaKota, negara, kodePos) values (14, 'Waitakere', 'New Zealand', '0782');
insert into kota (idKota, namaKota, negara, kodePos) values (15, 'Petrolia', 'Canada', 'N0N');
insert into kota (idKota, namaKota, negara, kodePos) values (16, 'Huangli', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (17, 'Garhi Khairo', 'Pakistan', '79050');
insert into kota (idKota, namaKota, negara, kodePos) values (18, 'Novi Sad', 'Serbia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (19, 'Ngilengan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (20, 'Turus', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (21, 'El Carmen', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (22, 'Basiao', 'Philippines', '5806');
insert into kota (idKota, namaKota, negara, kodePos) values (23, 'San Rafael', 'Philippines', '5039');
insert into kota (idKota, namaKota, negara, kodePos) values (24, 'Xinshi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (25, 'Langádhia', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (26, 'Dimitrovgrad', 'Serbia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (27, 'Sanjiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (28, 'Bartošovice', 'Czech Republic', '742 54');
insert into kota (idKota, namaKota, negara, kodePos) values (29, 'Mariinsk', 'Russia', '652156');
insert into kota (idKota, namaKota, negara, kodePos) values (30, 'Haicheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (31, 'As Sūq al Jadīd', 'Yemen', null);
insert into kota (idKota, namaKota, negara, kodePos) values (32, 'Maharagama', 'Sri Lanka', '10280');
insert into kota (idKota, namaKota, negara, kodePos) values (33, 'Sokolo', 'Mali', null);
insert into kota (idKota, namaKota, negara, kodePos) values (34, 'Paraíba do Sul', 'Brazil', '25850-000');
insert into kota (idKota, namaKota, negara, kodePos) values (35, 'Itajuípe', 'Brazil', '45630-000');
insert into kota (idKota, namaKota, negara, kodePos) values (36, 'Glubokiy', 'Russia', '368034');
insert into kota (idKota, namaKota, negara, kodePos) values (37, 'Bandung', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (38, 'Huashi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (39, 'Suci Kaler', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (40, 'Caimitillo', 'Panama', null);
insert into kota (idKota, namaKota, negara, kodePos) values (41, 'Negoslavci', 'Croatia', '32239');
insert into kota (idKota, namaKota, negara, kodePos) values (42, 'Muan', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (43, 'Tacna', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (44, 'Makato', 'Philippines', '5611');
insert into kota (idKota, namaKota, negara, kodePos) values (45, 'Michałowo', 'Poland', '16-050');
insert into kota (idKota, namaKota, negara, kodePos) values (46, 'Norrtälje', 'Sweden', '761 31');
insert into kota (idKota, namaKota, negara, kodePos) values (47, 'Old City', 'Palestinian Territory', null);
insert into kota (idKota, namaKota, negara, kodePos) values (48, 'Cergy-Pontoise', 'France', '95046 CEDEX 1');
insert into kota (idKota, namaKota, negara, kodePos) values (49, 'Sangojar', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (50, 'Áno Kalentíni', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (51, 'Ciheras', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (52, 'Lugovskoy', 'Russia', '628532');
insert into kota (idKota, namaKota, negara, kodePos) values (53, 'Tønsberg', 'Norway', '3114');
insert into kota (idKota, namaKota, negara, kodePos) values (54, 'Lazarevac', 'Serbia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (55, 'Kazan', 'Russia', '421991');
insert into kota (idKota, namaKota, negara, kodePos) values (56, 'Kurumoch', 'Russia', '443544');
insert into kota (idKota, namaKota, negara, kodePos) values (57, 'Třemošnice', 'Czech Republic', '538 43');
insert into kota (idKota, namaKota, negara, kodePos) values (58, 'Höshööt', 'Mongolia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (59, 'Duqu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (60, 'Drajak', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (61, 'Leninsk', 'Russia', '404622');
insert into kota (idKota, namaKota, negara, kodePos) values (62, 'Gaobu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (63, 'Croissy-sur-Seine', 'France', '78294 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (64, 'Oldřišov', 'Czech Republic', '747 33');
insert into kota (idKota, namaKota, negara, kodePos) values (65, 'Patos de Minas', 'Brazil', '38700-000');
insert into kota (idKota, namaKota, negara, kodePos) values (66, 'Priozërsk', 'Russia', '188760');
insert into kota (idKota, namaKota, negara, kodePos) values (67, 'Viana', 'Brazil', '65215-000');
insert into kota (idKota, namaKota, negara, kodePos) values (68, 'Cikadondongdesa', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (69, 'Nong Khai', 'Thailand', '48130');
insert into kota (idKota, namaKota, negara, kodePos) values (70, 'Pleszew', 'Poland', '63-301');
insert into kota (idKota, namaKota, negara, kodePos) values (71, 'Gojō', 'Japan', '648-0002');
insert into kota (idKota, namaKota, negara, kodePos) values (72, 'Shahe', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (73, 'Babakan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (74, 'San Juan', 'Philippines', '6227');
insert into kota (idKota, namaKota, negara, kodePos) values (75, 'Södertälje', 'Sweden', '151 44');
insert into kota (idKota, namaKota, negara, kodePos) values (76, 'Quanling', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (77, 'Buenavista', 'Colombia', '154848');
insert into kota (idKota, namaKota, negara, kodePos) values (78, 'Narukan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (79, 'Fylí', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (80, 'Wangcun', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (81, 'Limache', 'Chile', null);
insert into kota (idKota, namaKota, negara, kodePos) values (82, 'Chalon-sur-Saône', 'France', '71332 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (83, 'Lavezares', 'Philippines', '6404');
insert into kota (idKota, namaKota, negara, kodePos) values (84, 'Pravdinsk', 'Russia', '238402');
insert into kota (idKota, namaKota, negara, kodePos) values (85, 'Banjar Budakeling', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (86, 'Mabu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (87, 'Xinxu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (88, 'Gumalang', 'Philippines', '3312');
insert into kota (idKota, namaKota, negara, kodePos) values (89, 'Xiayang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (90, 'Umanggudang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (91, 'Langkap', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (92, 'Papetoai', 'French Polynesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (93, 'Mikhaylovsk', 'Russia', '243421');
insert into kota (idKota, namaKota, negara, kodePos) values (94, 'Créteil', 'France', '94049 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (95, 'Wielichowo', 'Poland', '64-050');
insert into kota (idKota, namaKota, negara, kodePos) values (96, 'Fier', 'Albania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (97, 'Buenavista', 'Mexico', '71730');
insert into kota (idKota, namaKota, negara, kodePos) values (98, 'Novosel’ye', 'Belarus', null);
insert into kota (idKota, namaKota, negara, kodePos) values (99, 'Daguma', 'Philippines', '1009');
insert into kota (idKota, namaKota, negara, kodePos) values (100, 'Boulogne-sur-Mer', 'France', '62222 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (101, 'Pamungguan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (102, 'San Sebastian', 'Philippines', '6714');
insert into kota (idKota, namaKota, negara, kodePos) values (103, 'Sumurber', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (104, 'Wasquehal', 'France', '59444 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (105, 'Rolândia', 'Brazil', '86600-000');
insert into kota (idKota, namaKota, negara, kodePos) values (106, 'Kadupinang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (107, 'Yudong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (108, 'Mont-Saint-Hilaire', 'Canada', 'J3H');
insert into kota (idKota, namaKota, negara, kodePos) values (109, 'Siak Sri Indrapura', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (110, 'Yancheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (111, 'Privolzhskiy', 'Russia', '413138');
insert into kota (idKota, namaKota, negara, kodePos) values (112, 'Saint-Priest', 'France', '69794 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (113, 'Yongning', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (114, 'Agrínio', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (115, 'Cañete', 'Chile', null);
insert into kota (idKota, namaKota, negara, kodePos) values (116, 'Xinhua', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (117, 'Adani', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (118, 'Zhuting', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (119, 'Hongshi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (120, 'Blahodatne', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (121, 'Sambopinggir', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (122, 'Gorelovo', 'Russia', '644091');
insert into kota (idKota, namaKota, negara, kodePos) values (123, 'Yulin', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (124, 'Huangtan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (125, 'Mae Lao', 'Thailand', '57250');
insert into kota (idKota, namaKota, negara, kodePos) values (126, 'Pakel', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (127, 'Aţ Ţafīlah', 'Jordan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (128, 'Yanhe', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (129, 'Banjar Tengahbelayu', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (130, 'København', 'Denmark', '1577');
insert into kota (idKota, namaKota, negara, kodePos) values (131, 'Bafoulabé', 'Mali', null);
insert into kota (idKota, namaKota, negara, kodePos) values (132, 'Karangnunggal', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (133, 'Vladikavkaz', 'Russia', '362049');
insert into kota (idKota, namaKota, negara, kodePos) values (134, 'Rosario', 'Philippines', '8504');
insert into kota (idKota, namaKota, negara, kodePos) values (135, 'Dean', 'United Kingdom', 'OX7');
insert into kota (idKota, namaKota, negara, kodePos) values (136, 'Vigo', 'Spain', '36215');
insert into kota (idKota, namaKota, negara, kodePos) values (137, 'Longjumeau', 'France', '91821 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (138, 'Redcliff', 'Zimbabwe', null);
insert into kota (idKota, namaKota, negara, kodePos) values (139, 'Sydney', 'Australia', '1009');
insert into kota (idKota, namaKota, negara, kodePos) values (140, 'Kopidlno', 'Czech Republic', '507 32');
insert into kota (idKota, namaKota, negara, kodePos) values (141, 'Oslo', 'Norway', '0789');
insert into kota (idKota, namaKota, negara, kodePos) values (142, 'Yushanpu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (143, 'Umeå', 'Sweden', '903 42');
insert into kota (idKota, namaKota, negara, kodePos) values (144, 'Baki', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (145, 'Baryshivka', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (146, 'Pedregulho', 'Brazil', '14470-000');
insert into kota (idKota, namaKota, negara, kodePos) values (147, 'Swellendam', 'South Africa', '6743');
insert into kota (idKota, namaKota, negara, kodePos) values (148, 'Lom Sak', 'Thailand', '67110');
insert into kota (idKota, namaKota, negara, kodePos) values (149, 'Doljevac', 'Serbia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (150, 'Fengyuan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (151, 'Sicaya', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (152, 'Hirado', 'Japan', '276-0017');
insert into kota (idKota, namaKota, negara, kodePos) values (153, 'Vulcan', 'Canada', 'V6M');
insert into kota (idKota, namaKota, negara, kodePos) values (154, 'Söderköping', 'Sweden', '614 31');
insert into kota (idKota, namaKota, negara, kodePos) values (155, 'Dos Quebradas', 'Colombia', '661008');
insert into kota (idKota, namaKota, negara, kodePos) values (156, 'Yanghu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (157, 'Caxarias', 'Portugal', '2435-042');
insert into kota (idKota, namaKota, negara, kodePos) values (158, 'Villa Atamisqui', 'Argentina', '4317');
insert into kota (idKota, namaKota, negara, kodePos) values (159, 'Velký Týnec', 'Czech Republic', '783 72');
insert into kota (idKota, namaKota, negara, kodePos) values (160, 'Lubrza', 'Poland', '66-218');
insert into kota (idKota, namaKota, negara, kodePos) values (161, 'Atsugi', 'Japan', '243-0007');
insert into kota (idKota, namaKota, negara, kodePos) values (162, 'Guiping', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (163, 'Si Somdet', 'Thailand', '95130');
insert into kota (idKota, namaKota, negara, kodePos) values (164, 'Samajie Ewenkeminzu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (165, 'Ghormach', 'Afghanistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (166, 'Cikotok', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (167, 'Mazatenango', 'Guatemala', '10001');
insert into kota (idKota, namaKota, negara, kodePos) values (168, 'Waiwejak', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (169, 'Xialu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (170, 'Chino', 'Japan', '520-0111');
insert into kota (idKota, namaKota, negara, kodePos) values (171, 'Strabychovo', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (172, 'Jingling', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (173, 'Kontiolahti', 'Finland', '81101');
insert into kota (idKota, namaKota, negara, kodePos) values (174, 'Fangshan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (175, 'Tomakomai', 'Japan', '882-1622');
insert into kota (idKota, namaKota, negara, kodePos) values (176, 'Jifeng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (177, 'Leninsk', 'Russia', '404622');
insert into kota (idKota, namaKota, negara, kodePos) values (178, 'Xiangride', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (179, 'Penghu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (180, 'Kopparberg', 'Sweden', '714 31');
insert into kota (idKota, namaKota, negara, kodePos) values (181, 'Šenčur', 'Slovenia', '4208');
insert into kota (idKota, namaKota, negara, kodePos) values (182, 'Chengzi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (183, 'Avdzaga', 'Mongolia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (184, 'Xicheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (185, 'Irosin', 'Philippines', '4707');
insert into kota (idKota, namaKota, negara, kodePos) values (186, 'Périgueux', 'France', '24004 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (187, 'Storuman', 'Sweden', '923 24');
insert into kota (idKota, namaKota, negara, kodePos) values (188, 'Sakharovo', 'Russia', '613840');
insert into kota (idKota, namaKota, negara, kodePos) values (189, 'Graz', 'Austria', '8047');
insert into kota (idKota, namaKota, negara, kodePos) values (190, 'Miras', 'Albania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (191, 'Celeirós', 'Portugal', '5060-016');
insert into kota (idKota, namaKota, negara, kodePos) values (192, 'Raposos', 'Brazil', '34400-000');
insert into kota (idKota, namaKota, negara, kodePos) values (193, 'Buga', 'Colombia', '763049');
insert into kota (idKota, namaKota, negara, kodePos) values (194, 'Salt Lake City', 'United States', '84170');
insert into kota (idKota, namaKota, negara, kodePos) values (195, 'Valsamáta', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (196, 'Mount Darwin', 'Zimbabwe', null);
insert into kota (idKota, namaKota, negara, kodePos) values (197, 'Tena', 'Ecuador', null);
insert into kota (idKota, namaKota, negara, kodePos) values (198, 'Agualva de Cima', 'Portugal', '2965-207');
insert into kota (idKota, namaKota, negara, kodePos) values (199, 'Kadukaung', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (200, 'Shiyan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (201, 'Bulumulyo', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (202, 'Banī Ḩassān', 'Tunisia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (203, 'Samayac', 'Guatemala', '10009');
insert into kota (idKota, namaKota, negara, kodePos) values (204, 'Mwembe', 'Tanzania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (205, 'Huzhuang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (206, 'Jombang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (207, 'Odeleite', 'Portugal', '8950-355');
insert into kota (idKota, namaKota, negara, kodePos) values (208, 'Sijing', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (209, 'Sremski Karlovci', 'Serbia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (210, 'Presa', 'Portugal', '3070-385');
insert into kota (idKota, namaKota, negara, kodePos) values (211, 'Wenping', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (212, 'Atimonan', 'Philippines', '4331');
insert into kota (idKota, namaKota, negara, kodePos) values (213, 'Praingkareha', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (214, 'Contraalmirante Cordero', 'Argentina', '8305');
insert into kota (idKota, namaKota, negara, kodePos) values (215, 'Cheqiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (216, 'Tomaszów Mazowiecki', 'Poland', '97-280');
insert into kota (idKota, namaKota, negara, kodePos) values (217, 'Gucheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (218, 'Xiangrong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (219, 'Chengxi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (220, 'Sison', 'Philippines', '8404');
insert into kota (idKota, namaKota, negara, kodePos) values (221, 'Saint-Marcellin', 'France', '38164 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (222, 'Pajić Polje', 'Bosnia and Herzegovina', null);
insert into kota (idKota, namaKota, negara, kodePos) values (223, 'Newport', 'United Kingdom', 'NR29');
insert into kota (idKota, namaKota, negara, kodePos) values (224, 'Saint-Maur-des-Fossés', 'France', '94109 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (225, 'Hamar', 'Norway', '2305');
insert into kota (idKota, namaKota, negara, kodePos) values (226, 'Hartola', 'Finland', '19601');
insert into kota (idKota, namaKota, negara, kodePos) values (227, 'Pule', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (228, 'Terrugem', 'Portugal', '2770-024');
insert into kota (idKota, namaKota, negara, kodePos) values (229, 'Uppsala', 'Sweden', '751 87');
insert into kota (idKota, namaKota, negara, kodePos) values (230, 'Ariquemes', 'Brazil', '78930-000');
insert into kota (idKota, namaKota, negara, kodePos) values (231, 'Tondabayashichō', 'Japan', '589-0013');
insert into kota (idKota, namaKota, negara, kodePos) values (232, 'Marinići', 'Croatia', '51216');
insert into kota (idKota, namaKota, negara, kodePos) values (233, 'Słotowa', 'Poland', '39-225');
insert into kota (idKota, namaKota, negara, kodePos) values (234, 'Jarošov nad Nežárkou', 'Czech Republic', '378 41');
insert into kota (idKota, namaKota, negara, kodePos) values (235, 'Pasirtujuhpuluh', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (236, 'Lubbock', 'United States', '79405');
insert into kota (idKota, namaKota, negara, kodePos) values (237, 'Sangallaya', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (238, 'Vorontsovka', 'Russia', '396449');
insert into kota (idKota, namaKota, negara, kodePos) values (239, 'Luboń', 'Poland', '62-031');
insert into kota (idKota, namaKota, negara, kodePos) values (240, 'Banjar Jabejero', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (241, 'Alejal', 'Philippines', '9205');
insert into kota (idKota, namaKota, negara, kodePos) values (242, 'Mexico', 'Philippines', '2021');
insert into kota (idKota, namaKota, negara, kodePos) values (243, 'Stěžery', 'Czech Republic', '503 21');
insert into kota (idKota, namaKota, negara, kodePos) values (244, 'Rashaant', 'Mongolia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (245, 'Rybatskoye', 'Russia', '196851');
insert into kota (idKota, namaKota, negara, kodePos) values (246, 'Mabalacat', 'Philippines', '2010');
insert into kota (idKota, namaKota, negara, kodePos) values (247, 'Saint Louis', 'United States', '63143');
insert into kota (idKota, namaKota, negara, kodePos) values (248, 'Starobelokurikha', 'Russia', '659633');
insert into kota (idKota, namaKota, negara, kodePos) values (249, 'Ngandangan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (250, 'Boromlya', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (251, 'La Tigra', 'Argentina', '5949');
insert into kota (idKota, namaKota, negara, kodePos) values (252, 'Brikama', 'Gambia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (253, 'Dunyāpur', 'Pakistan', '59111');
insert into kota (idKota, namaKota, negara, kodePos) values (254, 'Mmathubudukwane', 'Botswana', null);
insert into kota (idKota, namaKota, negara, kodePos) values (255, 'Pasarkolot', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (256, 'Bacnotan', 'Philippines', '2515');
insert into kota (idKota, namaKota, negara, kodePos) values (257, 'Oepula', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (258, 'Borek Wielkopolski', 'Poland', '63-810');
insert into kota (idKota, namaKota, negara, kodePos) values (259, 'Caujul', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (260, 'Krajan Gajahmati', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (261, 'Kropachëvo', 'Russia', '456030');
insert into kota (idKota, namaKota, negara, kodePos) values (262, 'Nový Bor', 'Czech Republic', '473 01');
insert into kota (idKota, namaKota, negara, kodePos) values (263, 'Recife', 'Brazil', '50000-000');
insert into kota (idKota, namaKota, negara, kodePos) values (264, 'Marang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (265, 'Rzeczenica', 'Poland', '77-304');
insert into kota (idKota, namaKota, negara, kodePos) values (266, 'Uujim', 'Mongolia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (267, 'Odienné', 'Ivory Coast', null);
insert into kota (idKota, namaKota, negara, kodePos) values (268, 'Émpa', 'Cyprus', null);
insert into kota (idKota, namaKota, negara, kodePos) values (269, 'Loacan', 'Philippines', '2612');
insert into kota (idKota, namaKota, negara, kodePos) values (270, 'Cikarang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (271, 'Bankaw', 'Philippines', '1211');
insert into kota (idKota, namaKota, negara, kodePos) values (272, 'Kudamatsu', 'Japan', '745-0654');
insert into kota (idKota, namaKota, negara, kodePos) values (273, 'Yurovka', 'Russia', '353426');
insert into kota (idKota, namaKota, negara, kodePos) values (274, 'Venado Tuerto', 'Argentina', '2600');
insert into kota (idKota, namaKota, negara, kodePos) values (275, 'Valašská Bystřice', 'Czech Republic', '756 27');
insert into kota (idKota, namaKota, negara, kodePos) values (276, 'Zubtsov', 'Russia', '172318');
insert into kota (idKota, namaKota, negara, kodePos) values (277, 'Chichinales', 'Argentina', '8326');
insert into kota (idKota, namaKota, negara, kodePos) values (278, 'Nanfeng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (279, 'Mayqayyng', 'Kazakhstan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (280, 'Oeiras', 'Brazil', '64500-000');
insert into kota (idKota, namaKota, negara, kodePos) values (281, 'Shiye', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (282, 'Sangzhou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (283, 'San Juan', 'Mexico', '30540');
insert into kota (idKota, namaKota, negara, kodePos) values (284, 'Xinhua', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (285, 'Sendangagung', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (286, 'Södertälje', 'Sweden', '151 52');
insert into kota (idKota, namaKota, negara, kodePos) values (287, 'Ilha de Moçambique', 'Mozambique', null);
insert into kota (idKota, namaKota, negara, kodePos) values (288, 'Norsborg', 'Sweden', '145 69');
insert into kota (idKota, namaKota, negara, kodePos) values (289, 'Yershov', 'Russia', '442080');
insert into kota (idKota, namaKota, negara, kodePos) values (290, 'Balkh', 'Afghanistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (291, 'Huurch', 'Mongolia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (292, 'Novomoskovsk', 'Russia', '301767');
insert into kota (idKota, namaKota, negara, kodePos) values (293, 'Mizusawa', 'Japan', '999-7542');
insert into kota (idKota, namaKota, negara, kodePos) values (294, 'Wuluo', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (295, 'La Loma', 'Mexico', '92148');
insert into kota (idKota, namaKota, negara, kodePos) values (296, 'Nelspruit', 'South Africa', '1360');
insert into kota (idKota, namaKota, negara, kodePos) values (297, 'Belo Jardim', 'Brazil', '55150-000');
insert into kota (idKota, namaKota, negara, kodePos) values (298, 'Kamyanyuki', 'Belarus', null);
insert into kota (idKota, namaKota, negara, kodePos) values (299, 'Kresek', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (300, 'Daqian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (301, 'Uchimaru', 'Japan', '407-0002');
insert into kota (idKota, namaKota, negara, kodePos) values (302, 'Rajapeni', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (303, 'El Benque', 'Honduras', null);
insert into kota (idKota, namaKota, negara, kodePos) values (304, 'Dobje pri Planini', 'Slovenia', '3224');
insert into kota (idKota, namaKota, negara, kodePos) values (305, 'Toledo', 'United States', '43666');
insert into kota (idKota, namaKota, negara, kodePos) values (306, 'Napnapan', 'Philippines', '5021');
insert into kota (idKota, namaKota, negara, kodePos) values (307, 'Sari', 'Iran', null);
insert into kota (idKota, namaKota, negara, kodePos) values (308, 'Kināna', 'Sudan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (309, 'Gaoqiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (310, 'Montfort-sur-Meu', 'France', '35164 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (311, 'Ekazhevo', 'Russia', '386150');
insert into kota (idKota, namaKota, negara, kodePos) values (312, 'Paris 16', 'France', '75215 CEDEX 16');
insert into kota (idKota, namaKota, negara, kodePos) values (313, 'Kiruna', 'Sweden', '981 31');
insert into kota (idKota, namaKota, negara, kodePos) values (314, 'Plan de Ayala', 'Mexico', '29601');
insert into kota (idKota, namaKota, negara, kodePos) values (315, 'Trinidad', 'Uruguay', null);
insert into kota (idKota, namaKota, negara, kodePos) values (316, 'Jiuchi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (317, 'Cibugel', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (318, 'Horton', 'United Kingdom', 'BS37');
insert into kota (idKota, namaKota, negara, kodePos) values (319, 'Casal Novo', 'Portugal', '6100-218');
insert into kota (idKota, namaKota, negara, kodePos) values (320, 'Shahr-e Qods', 'Iran', null);
insert into kota (idKota, namaKota, negara, kodePos) values (321, 'Salta', 'Argentina', '4400');
insert into kota (idKota, namaKota, negara, kodePos) values (322, 'Jinsheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (323, 'Tigbao', 'Philippines', '7043');
insert into kota (idKota, namaKota, negara, kodePos) values (324, 'Tanumshede', 'Sweden', '457 81');
insert into kota (idKota, namaKota, negara, kodePos) values (325, 'Skopje', 'Macedonia', '1040');
insert into kota (idKota, namaKota, negara, kodePos) values (326, 'Ustynivka', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (327, 'Oyonnax', 'France', '01117 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (328, 'Emnambithi-Ladysmith', 'South Africa', '3384');
insert into kota (idKota, namaKota, negara, kodePos) values (329, 'Lethbridge', 'Canada', 'T1K');
insert into kota (idKota, namaKota, negara, kodePos) values (330, 'Koktokay', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (331, 'Wulin', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (332, 'Maragogipe', 'Brazil', '44420-000');
insert into kota (idKota, namaKota, negara, kodePos) values (333, 'Suhong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (334, 'Bayt Wazan', 'Palestinian Territory', null);
insert into kota (idKota, namaKota, negara, kodePos) values (335, 'Toledo', 'United States', '43610');
insert into kota (idKota, namaKota, negara, kodePos) values (336, 'Austin', 'United States', '78769');
insert into kota (idKota, namaKota, negara, kodePos) values (337, 'Nuevo Chamelecón', 'Honduras', null);
insert into kota (idKota, namaKota, negara, kodePos) values (338, 'Los Cedrales', 'Paraguay', null);
insert into kota (idKota, namaKota, negara, kodePos) values (339, 'Tarikolot', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (340, 'Tingo María', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (341, 'Longcheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (342, 'Tuntum', 'Brazil', '65763-000');
insert into kota (idKota, namaKota, negara, kodePos) values (343, 'Manukaka', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (344, 'Comodoro Rivadavia', 'Argentina', '9000');
insert into kota (idKota, namaKota, negara, kodePos) values (345, 'Tejen', 'Turkmenistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (346, 'Dandu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (347, 'Nakhon Nayok', 'Thailand', '26120');
insert into kota (idKota, namaKota, negara, kodePos) values (348, 'Chivilcoy', 'Argentina', '5571');
insert into kota (idKota, namaKota, negara, kodePos) values (349, 'Zaozhuang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (350, 'Osielsko', 'Poland', '86-031');
insert into kota (idKota, namaKota, negara, kodePos) values (351, 'Stamáta', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (352, 'Vân Canh', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (353, 'Osiedle-Nowiny', 'Poland', '93-154');
insert into kota (idKota, namaKota, negara, kodePos) values (354, 'Doumuhu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (355, 'Chigasaki', 'Japan', '253-0041');
insert into kota (idKota, namaKota, negara, kodePos) values (356, 'Pastores', 'Guatemala', '03003');
insert into kota (idKota, namaKota, negara, kodePos) values (357, 'Nueva Germania', 'Paraguay', null);
insert into kota (idKota, namaKota, negara, kodePos) values (358, 'Duowa', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (359, 'Tominian', 'Mali', null);
insert into kota (idKota, namaKota, negara, kodePos) values (360, 'Ochër', 'Russia', '617140');
insert into kota (idKota, namaKota, negara, kodePos) values (361, 'Aqtöbe', 'Kazakhstan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (362, 'Beaufort West', 'South Africa', '6973');
insert into kota (idKota, namaKota, negara, kodePos) values (363, 'Huating', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (364, 'Saitama', 'Japan', '343-0801');
insert into kota (idKota, namaKota, negara, kodePos) values (365, 'Biggar', 'Canada', 'N1S');
insert into kota (idKota, namaKota, negara, kodePos) values (366, 'Inya', 'Russia', '646604');
insert into kota (idKota, namaKota, negara, kodePos) values (367, 'Dianwan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (368, 'Souflí', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (369, 'Shatki', 'Russia', '607700');
insert into kota (idKota, namaKota, negara, kodePos) values (370, 'Tandag', 'Philippines', '8300');
insert into kota (idKota, namaKota, negara, kodePos) values (371, 'Haoraoshan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (372, 'Ximei', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (373, 'Fagersta', 'Sweden', '737 42');
insert into kota (idKota, namaKota, negara, kodePos) values (374, 'Bulungu', 'Democratic Republic of the Congo', null);
insert into kota (idKota, namaKota, negara, kodePos) values (375, 'Aleg', 'Mauritania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (376, 'Ar Riqqah', 'Kuwait', null);
insert into kota (idKota, namaKota, negara, kodePos) values (377, 'San Jorge', 'Nicaragua', null);
insert into kota (idKota, namaKota, negara, kodePos) values (378, 'Chengdong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (379, 'La Roxas', 'Philippines', '6217');
insert into kota (idKota, namaKota, negara, kodePos) values (380, 'Tomiya', 'Japan', '981-3311');
insert into kota (idKota, namaKota, negara, kodePos) values (381, 'Hedong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (382, 'Xin’an', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (383, 'Minami-rinkan', 'Japan', '246-0038');
insert into kota (idKota, namaKota, negara, kodePos) values (384, 'Lama', 'Portugal', '4890-372');
insert into kota (idKota, namaKota, negara, kodePos) values (385, 'Tomakomai', 'Japan', '882-1622');
insert into kota (idKota, namaKota, negara, kodePos) values (386, 'Rodolívos', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (387, 'Mirocin', 'Poland', '37-565');
insert into kota (idKota, namaKota, negara, kodePos) values (388, 'Amaury', 'Mauritius', null);
insert into kota (idKota, namaKota, negara, kodePos) values (389, 'Waco', 'United States', '76705');
insert into kota (idKota, namaKota, negara, kodePos) values (390, 'Luna', 'Philippines', '3813');
insert into kota (idKota, namaKota, negara, kodePos) values (391, 'Lishu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (392, 'Sopron', 'Hungary', '9404');
insert into kota (idKota, namaKota, negara, kodePos) values (393, 'Yevpatoriya', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (394, 'Jiaqu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (395, 'Noshiro', 'Japan', '921-8804');
insert into kota (idKota, namaKota, negara, kodePos) values (396, 'Malusac', 'Philippines', '2005');
insert into kota (idKota, namaKota, negara, kodePos) values (397, 'Pieńsk', 'Poland', '59-930');
insert into kota (idKota, namaKota, negara, kodePos) values (398, 'Lazaro Cardenas', 'Mexico', '27944');
insert into kota (idKota, namaKota, negara, kodePos) values (399, 'Awilega', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (400, 'Voyskovitsy', 'Russia', '188360');
insert into kota (idKota, namaKota, negara, kodePos) values (401, 'Malitubog', 'Philippines', '9413');
insert into kota (idKota, namaKota, negara, kodePos) values (402, 'Wuma', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (403, 'Penhascoso', 'Portugal', '6120-625');
insert into kota (idKota, namaKota, negara, kodePos) values (404, 'Zhangqiang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (405, 'Stupino', 'Russia', '142806');
insert into kota (idKota, namaKota, negara, kodePos) values (406, 'Bakalang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (407, 'Laborde', 'Argentina', '2657');
insert into kota (idKota, namaKota, negara, kodePos) values (408, 'Khōst', 'Afghanistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (409, 'Kyosai', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (410, 'Ħamrun', 'Malta', 'HMR');
insert into kota (idKota, namaKota, negara, kodePos) values (411, 'Yumbo', 'Colombia', '760508');
insert into kota (idKota, namaKota, negara, kodePos) values (412, 'Itambacuri', 'Brazil', '39830-000');
insert into kota (idKota, namaKota, negara, kodePos) values (413, 'Altamira', 'Venezuela', null);
insert into kota (idKota, namaKota, negara, kodePos) values (414, 'Pisão', 'Portugal', '3220-331');
insert into kota (idKota, namaKota, negara, kodePos) values (415, 'Mocho', 'Jamaica', null);
insert into kota (idKota, namaKota, negara, kodePos) values (416, 'Ilebo', 'Democratic Republic of the Congo', null);
insert into kota (idKota, namaKota, negara, kodePos) values (417, 'Ketanen', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (418, 'Pervoavgustovskiy', 'Russia', '307513');
insert into kota (idKota, namaKota, negara, kodePos) values (419, 'Makiwalo', 'Philippines', '1743');
insert into kota (idKota, namaKota, negara, kodePos) values (420, 'Tvrdonice', 'Czech Republic', '691 53');
insert into kota (idKota, namaKota, negara, kodePos) values (421, 'Maguyam', 'Philippines', '9400');
insert into kota (idKota, namaKota, negara, kodePos) values (422, 'Pasonobenu', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (423, 'Quintã', 'Portugal', '4620-729');
insert into kota (idKota, namaKota, negara, kodePos) values (424, 'Chřibská', 'Czech Republic', '407 44');
insert into kota (idKota, namaKota, negara, kodePos) values (425, 'Pale', 'Bosnia and Herzegovina', null);
insert into kota (idKota, namaKota, negara, kodePos) values (426, 'Waegwan', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (427, 'Antipino', 'Russia', '625516');
insert into kota (idKota, namaKota, negara, kodePos) values (428, 'Troparëvo', 'Russia', '141662');
insert into kota (idKota, namaKota, negara, kodePos) values (429, 'Cap-Santé', 'Canada', 'N0H');
insert into kota (idKota, namaKota, negara, kodePos) values (430, 'Turan', 'Russia', '668510');
insert into kota (idKota, namaKota, negara, kodePos) values (431, 'Wat Sing', 'Thailand', '17120');
insert into kota (idKota, namaKota, negara, kodePos) values (432, 'Kíti', 'Cyprus', null);
insert into kota (idKota, namaKota, negara, kodePos) values (433, 'Lethem', 'Guyana', null);
insert into kota (idKota, namaKota, negara, kodePos) values (434, 'Kedatuan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (435, 'Wang Saphung', 'Thailand', '42130');
insert into kota (idKota, namaKota, negara, kodePos) values (436, 'Gangmian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (437, 'Shar', 'Kazakhstan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (438, 'Andkhōy', 'Afghanistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (439, 'Vykhino-Zhulebino', 'Russia', '172372');
insert into kota (idKota, namaKota, negara, kodePos) values (440, 'Skalánion', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (441, 'Fontanka', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (442, 'Fakel', 'Russia', '427168');
insert into kota (idKota, namaKota, negara, kodePos) values (443, 'Chisec', 'Guatemala', '18006');
insert into kota (idKota, namaKota, negara, kodePos) values (444, 'Jiangchi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (445, 'Cerna', 'Croatia', '32272');
insert into kota (idKota, namaKota, negara, kodePos) values (446, 'Sumuragung', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (447, 'Santo Domingo', 'Philippines', '4508');
insert into kota (idKota, namaKota, negara, kodePos) values (448, 'Salaverry', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (449, 'Uinskoye', 'Russia', '617520');
insert into kota (idKota, namaKota, negara, kodePos) values (450, 'Huddinge', 'Sweden', '141 38');
insert into kota (idKota, namaKota, negara, kodePos) values (451, 'Lipovljani', 'Croatia', '44322');
insert into kota (idKota, namaKota, negara, kodePos) values (452, 'Luofang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (453, 'Henggang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (454, 'Buenlag', 'Philippines', '2424');
insert into kota (idKota, namaKota, negara, kodePos) values (455, 'Pābna', 'Bangladesh', '6602');
insert into kota (idKota, namaKota, negara, kodePos) values (456, 'Maszkienice', 'Poland', '32-854');
insert into kota (idKota, namaKota, negara, kodePos) values (457, 'Shangjin', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (458, 'Vershino-Shakhtaminskiy', 'Russia', '673613');
insert into kota (idKota, namaKota, negara, kodePos) values (459, 'Shiraoka', 'Japan', '349-0218');
insert into kota (idKota, namaKota, negara, kodePos) values (460, 'Nan', 'Thailand', '55000');
insert into kota (idKota, namaKota, negara, kodePos) values (461, 'Marcara', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (462, 'Höshööt', 'Mongolia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (463, 'Nanjie', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (464, 'Petroúpolis', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (465, 'Bartolomé Masó', 'Cuba', null);
insert into kota (idKota, namaKota, negara, kodePos) values (466, 'Safakulevo', 'Russia', '641080');
insert into kota (idKota, namaKota, negara, kodePos) values (467, 'Vlachovo Březí', 'Czech Republic', '384 22');
insert into kota (idKota, namaKota, negara, kodePos) values (468, 'Aqqan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (469, 'Oke Mesi', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (470, 'Tiebiancheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (471, 'Funabashi', 'Japan', '992-0325');
insert into kota (idKota, namaKota, negara, kodePos) values (472, 'Koski Tl', 'Finland', '31501');
insert into kota (idKota, namaKota, negara, kodePos) values (473, 'Olovyannaya', 'Russia', '674504');
insert into kota (idKota, namaKota, negara, kodePos) values (474, 'Colesberg', 'South Africa', '9922');
insert into kota (idKota, namaKota, negara, kodePos) values (475, 'Langpas', 'Philippines', '1053');
insert into kota (idKota, namaKota, negara, kodePos) values (476, 'Una', 'Brazil', '45690-000');
insert into kota (idKota, namaKota, negara, kodePos) values (477, 'Kubangkondang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (478, 'Kaishantun', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (479, 'Silikatnyy', 'Russia', '433396');
insert into kota (idKota, namaKota, negara, kodePos) values (480, 'Jiumen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (481, 'Mkushi', 'Zambia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (482, 'Lila', 'Philippines', '6304');
insert into kota (idKota, namaKota, negara, kodePos) values (483, 'Suḩayl Shibām', 'Yemen', null);
insert into kota (idKota, namaKota, negara, kodePos) values (484, 'Puerres', 'Colombia', '523548');
insert into kota (idKota, namaKota, negara, kodePos) values (485, 'Al Jīzah', 'Egypt', null);
insert into kota (idKota, namaKota, negara, kodePos) values (486, 'Viļaka', 'Latvia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (487, 'Beigou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (488, 'Karangsuko', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (489, 'Pevek', 'Russia', '689400');
insert into kota (idKota, namaKota, negara, kodePos) values (490, 'Funabashi', 'Japan', '992-0325');
insert into kota (idKota, namaKota, negara, kodePos) values (491, 'Kítsi', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (492, 'La Unión', 'El Salvador', null);
insert into kota (idKota, namaKota, negara, kodePos) values (493, 'Frampol', 'Poland', '23-440');
insert into kota (idKota, namaKota, negara, kodePos) values (494, 'Puerto Iguazú', 'Argentina', '3370');
insert into kota (idKota, namaKota, negara, kodePos) values (495, 'Pancoran', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (496, 'Fangtian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (497, 'Kajiado', 'Kenya', null);
insert into kota (idKota, namaKota, negara, kodePos) values (498, 'Overyata', 'Russia', '617071');
insert into kota (idKota, namaKota, negara, kodePos) values (499, 'Makiwalo', 'Philippines', '1743');
insert into kota (idKota, namaKota, negara, kodePos) values (500, 'Nonggunong', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (501, 'Changning', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (502, 'Kwali', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (503, 'Saint George''s', 'Grenada', null);
insert into kota (idKota, namaKota, negara, kodePos) values (504, 'Moñitos', 'Colombia', '231008');
insert into kota (idKota, namaKota, negara, kodePos) values (505, 'San Casimiro', 'Philippines', '4332');
insert into kota (idKota, namaKota, negara, kodePos) values (506, 'Mandangoa', 'Philippines', '9006');
insert into kota (idKota, namaKota, negara, kodePos) values (507, 'Tanudan', 'Philippines', '3805');
insert into kota (idKota, namaKota, negara, kodePos) values (508, 'Lipov', 'Czech Republic', '696 72');
insert into kota (idKota, namaKota, negara, kodePos) values (509, 'Bansalan', 'Philippines', '8005');
insert into kota (idKota, namaKota, negara, kodePos) values (510, 'Arauca', 'Colombia', '810009');
insert into kota (idKota, namaKota, negara, kodePos) values (511, 'Jovim', 'Portugal', '4510-005');
insert into kota (idKota, namaKota, negara, kodePos) values (512, 'Pleiku', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (513, 'Belén', 'Uruguay', null);
insert into kota (idKota, namaKota, negara, kodePos) values (514, 'Stockholm', 'Sweden', '115 32');
insert into kota (idKota, namaKota, negara, kodePos) values (515, 'Bayt ‘Anān', 'Palestinian Territory', null);
insert into kota (idKota, namaKota, negara, kodePos) values (516, 'Pocsi', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (517, 'Głuchów', 'Poland', '96-130');
insert into kota (idKota, namaKota, negara, kodePos) values (518, 'Rudnyy', 'Kazakhstan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (519, 'Obudu', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (520, 'Beopwon', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (521, 'Basud', 'Philippines', '4608');
insert into kota (idKota, namaKota, negara, kodePos) values (522, 'Huangzhuang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (523, 'Barrancas', 'Colombia', '443049');
insert into kota (idKota, namaKota, negara, kodePos) values (524, 'Shuangjie', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (525, 'Banraeaba Village', 'Kiribati', null);
insert into kota (idKota, namaKota, negara, kodePos) values (526, 'Rungkang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (527, 'Pagelaran', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (528, 'San Miguel Chicaj', 'Guatemala', '15002');
insert into kota (idKota, namaKota, negara, kodePos) values (529, 'Obita', 'Japan', '859-0416');
insert into kota (idKota, namaKota, negara, kodePos) values (530, 'Ijuí', 'Brazil', '98700-000');
insert into kota (idKota, namaKota, negara, kodePos) values (531, 'Manolo Fortich', 'Philippines', '8703');
insert into kota (idKota, namaKota, negara, kodePos) values (532, 'Gelang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (533, 'Vancouver', 'United States', '98682');
insert into kota (idKota, namaKota, negara, kodePos) values (534, 'Nangkasari', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (535, 'Danirai', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (536, 'Jundian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (537, 'Micheng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (538, 'Osias', 'Philippines', '1550');
insert into kota (idKota, namaKota, negara, kodePos) values (539, 'La Cruz', 'Costa Rica', '51001');
insert into kota (idKota, namaKota, negara, kodePos) values (540, 'Seongnam-si', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (541, 'Outokumpu', 'Finland', '83501');
insert into kota (idKota, namaKota, negara, kodePos) values (542, 'Pridonskoy', 'Russia', '394091');
insert into kota (idKota, namaKota, negara, kodePos) values (543, 'Beichan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (544, 'Hamberang Sabrang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (545, 'Benger', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (546, 'Blokdesa Situgede', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (547, 'Vuka', 'Croatia', '31403');
insert into kota (idKota, namaKota, negara, kodePos) values (548, 'Layo', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (549, 'Jingkou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (550, 'Hexi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (551, 'Bilopillya', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (552, 'Pinheiro Machado', 'Brazil', '96470-000');
insert into kota (idKota, namaKota, negara, kodePos) values (553, 'Dallas', 'United States', '75372');
insert into kota (idKota, namaKota, negara, kodePos) values (554, 'Tegalsari', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (555, 'Meizhou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (556, 'Montbéliard', 'France', '25215 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (557, 'Chengui', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (558, 'Chupa', 'Russia', '186670');
insert into kota (idKota, namaKota, negara, kodePos) values (559, 'Salaza', 'Philippines', '2211');
insert into kota (idKota, namaKota, negara, kodePos) values (560, 'Turangi', 'New Zealand', '3382');
insert into kota (idKota, namaKota, negara, kodePos) values (561, 'Valday', 'Russia', '175419');
insert into kota (idKota, namaKota, negara, kodePos) values (562, 'Pho Thale', 'Thailand', '66130');
insert into kota (idKota, namaKota, negara, kodePos) values (563, 'Ketanggungan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (564, 'San Pedro', 'Argentina', '4500');
insert into kota (idKota, namaKota, negara, kodePos) values (565, 'Białobrzegi', 'Poland', '37-114');
insert into kota (idKota, namaKota, negara, kodePos) values (566, 'Lavezares', 'Philippines', '6404');
insert into kota (idKota, namaKota, negara, kodePos) values (567, 'Jambesari', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (568, 'Villejuif', 'France', '94804 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (569, 'Głuchów', 'Poland', '96-130');
insert into kota (idKota, namaKota, negara, kodePos) values (570, 'Manzë', 'Albania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (571, 'Petaẖ Tiqwa', 'Israel', null);
insert into kota (idKota, namaKota, negara, kodePos) values (572, 'Bác Ái', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (573, 'Sémbé', 'Republic of the Congo', null);
insert into kota (idKota, namaKota, negara, kodePos) values (574, 'Dongjiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (575, 'Buena Vista', 'Bolivia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (576, 'Kongtian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (577, 'Huxiaoqiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (578, 'Bobonan', 'Philippines', '2437');
insert into kota (idKota, namaKota, negara, kodePos) values (579, 'Apengjiang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (580, 'Riga', 'Latvia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (581, 'Hedaru', 'Tanzania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (582, 'Kokubunji', 'Japan', '952-0304');
insert into kota (idKota, namaKota, negara, kodePos) values (583, 'Storuman', 'Sweden', '923 98');
insert into kota (idKota, namaKota, negara, kodePos) values (584, 'Haebaru', 'Japan', '904-2311');
insert into kota (idKota, namaKota, negara, kodePos) values (585, 'Jefferson City', 'United States', '65110');
insert into kota (idKota, namaKota, negara, kodePos) values (586, 'Skhodnya', 'Russia', '143020');
insert into kota (idKota, namaKota, negara, kodePos) values (587, 'La Paz', 'Uruguay', null);
insert into kota (idKota, namaKota, negara, kodePos) values (588, 'Kruisfontein', 'South Africa', '2661');
insert into kota (idKota, namaKota, negara, kodePos) values (589, 'Ujiie', 'Japan', '329-1311');
insert into kota (idKota, namaKota, negara, kodePos) values (590, 'Corgo', 'Portugal', '4620-357');
insert into kota (idKota, namaKota, negara, kodePos) values (591, 'Mainit', 'Philippines', '8407');
insert into kota (idKota, namaKota, negara, kodePos) values (592, 'Banayoyo', 'Philippines', '2708');
insert into kota (idKota, namaKota, negara, kodePos) values (593, 'Xiehu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (594, 'Qilong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (595, 'Laborde', 'Argentina', '2657');
insert into kota (idKota, namaKota, negara, kodePos) values (596, 'Ganhe', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (597, 'Caohe', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (598, 'Cilolongokan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (599, 'Clearwater', 'United States', '34620');
insert into kota (idKota, namaKota, negara, kodePos) values (600, 'Chybie', 'Poland', '43-520');
insert into kota (idKota, namaKota, negara, kodePos) values (601, 'Gorzów Śląski', 'Poland', '46-310');
insert into kota (idKota, namaKota, negara, kodePos) values (602, 'Cherëmushki', 'Russia', '142817');
insert into kota (idKota, namaKota, negara, kodePos) values (603, 'Banjar Ponggang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (604, 'Uglich', 'Russia', '152616');
insert into kota (idKota, namaKota, negara, kodePos) values (605, 'Gora', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (606, 'Algarvia', 'Portugal', '9630-224');
insert into kota (idKota, namaKota, negara, kodePos) values (607, 'Pingshan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (608, 'Joroan', 'Philippines', '6007');
insert into kota (idKota, namaKota, negara, kodePos) values (609, 'Yuanqiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (610, 'Niort', 'France', '79021 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (611, 'Stubno', 'Poland', '37-723');
insert into kota (idKota, namaKota, negara, kodePos) values (612, 'Dolní Dunajovice', 'Czech Republic', '691 85');
insert into kota (idKota, namaKota, negara, kodePos) values (613, 'Tomakomai', 'Japan', '882-1622');
insert into kota (idKota, namaKota, negara, kodePos) values (614, 'Gros Morne', 'Haiti', null);
insert into kota (idKota, namaKota, negara, kodePos) values (615, 'Galatás', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (616, 'Novoul’yanovsk', 'Russia', '433300');
insert into kota (idKota, namaKota, negara, kodePos) values (617, 'Pingshanhu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (618, 'Camindangan', 'Philippines', '7015');
insert into kota (idKota, namaKota, negara, kodePos) values (619, 'Villeneuve-la-Garenne', 'France', '92398 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (620, 'Carcassonne', 'France', '11020 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (621, 'Yongfeng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (622, 'Knivsta', 'Sweden', '741 72');
insert into kota (idKota, namaKota, negara, kodePos) values (623, 'Skopje', 'Macedonia', '1040');
insert into kota (idKota, namaKota, negara, kodePos) values (624, 'Villa Bisonó', 'Dominican Republic', '11105');
insert into kota (idKota, namaKota, negara, kodePos) values (625, 'Krasnyy Profintern', 'Russia', '161213');
insert into kota (idKota, namaKota, negara, kodePos) values (626, 'Insua', 'Portugal', '4930-250');
insert into kota (idKota, namaKota, negara, kodePos) values (627, 'Pensacola', 'United States', '32595');
insert into kota (idKota, namaKota, negara, kodePos) values (628, 'Mauloo', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (629, 'Divo', 'Ivory Coast', null);
insert into kota (idKota, namaKota, negara, kodePos) values (630, 'Santa Fe de la Vera Cruz', 'Argentina', '3001');
insert into kota (idKota, namaKota, negara, kodePos) values (631, 'Chengbei', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (632, 'Anren Chengguanzhen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (633, 'Sindangsari', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (634, 'Florencia', 'Colombia', '195047');
insert into kota (idKota, namaKota, negara, kodePos) values (635, 'Labège', 'France', '31673 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (636, 'Āshkhāneh', 'Iran', null);
insert into kota (idKota, namaKota, negara, kodePos) values (637, 'Novovladykino', 'Russia', '659436');
insert into kota (idKota, namaKota, negara, kodePos) values (638, 'Bonavista', 'Canada', 'E8M');
insert into kota (idKota, namaKota, negara, kodePos) values (639, 'Kratovo', 'Russia', '142452');
insert into kota (idKota, namaKota, negara, kodePos) values (640, 'Chastyye', 'Russia', '617191');
insert into kota (idKota, namaKota, negara, kodePos) values (641, 'Péfki', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (642, 'Aulnay-sous-Bois', 'France', '93616 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (643, 'Jatibonico', 'Cuba', null);
insert into kota (idKota, namaKota, negara, kodePos) values (644, 'Ţawr al Bāḩah', 'Yemen', null);
insert into kota (idKota, namaKota, negara, kodePos) values (645, 'Kout na Šumavě', 'Czech Republic', '345 02');
insert into kota (idKota, namaKota, negara, kodePos) values (646, 'Katsina', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (647, 'Yasothon', 'Thailand', '35000');
insert into kota (idKota, namaKota, negara, kodePos) values (648, 'Byerazino', 'Belarus', null);
insert into kota (idKota, namaKota, negara, kodePos) values (649, 'Grevená', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (650, 'Arlöv', 'Sweden', '232 24');
insert into kota (idKota, namaKota, negara, kodePos) values (651, 'Rousínov', 'Czech Republic', '683 01');
insert into kota (idKota, namaKota, negara, kodePos) values (652, 'Isheyevka', 'Russia', '433310');
insert into kota (idKota, namaKota, negara, kodePos) values (653, 'Mnogoudobnoye', 'Russia', '416305');
insert into kota (idKota, namaKota, negara, kodePos) values (654, 'Podporozh’ye', 'Russia', '187789');
insert into kota (idKota, namaKota, negara, kodePos) values (655, 'Nîmes', 'France', '30904 CEDEX 9');
insert into kota (idKota, namaKota, negara, kodePos) values (656, 'Novopokrovka', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (657, 'Vitoria-Gasteiz', 'Spain', '01010');
insert into kota (idKota, namaKota, negara, kodePos) values (658, 'Castries', 'Saint Lucia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (659, 'Kwikila', 'Papua New Guinea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (660, 'Yur’yevets', 'Russia', '155450');
insert into kota (idKota, namaKota, negara, kodePos) values (661, 'Baie-Saint-Paul', 'Canada', 'G3Z');
insert into kota (idKota, namaKota, negara, kodePos) values (662, 'Xiangrong', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (663, 'Bielsk Podlaski', 'Poland', '17-102');
insert into kota (idKota, namaKota, negara, kodePos) values (664, 'Florencia', 'Colombia', '195047');
insert into kota (idKota, namaKota, negara, kodePos) values (665, 'Temorlorong', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (666, 'Sukadana', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (667, 'Nürnberg', 'Germany', '90411');
insert into kota (idKota, namaKota, negara, kodePos) values (668, 'Xiapu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (669, 'Sedlčany', 'Czech Republic', '264 01');
insert into kota (idKota, namaKota, negara, kodePos) values (670, 'Praia de Mira', 'Portugal', '3070-725');
insert into kota (idKota, namaKota, negara, kodePos) values (671, 'Turi', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (672, 'Paulpietersburg', 'South Africa', '3185');
insert into kota (idKota, namaKota, negara, kodePos) values (673, 'Xinghai', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (674, 'Mintang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (675, 'Catayauan', 'Philippines', '3509');
insert into kota (idKota, namaKota, negara, kodePos) values (676, 'Xin’an', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (677, 'Stradbally', 'Ireland', 'Y34');
insert into kota (idKota, namaKota, negara, kodePos) values (678, 'Taishanmiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (679, 'Hushi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (680, 'Lukou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (681, 'Padangtepung', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (682, 'Fangshan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (683, 'Jiabeiyan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (684, 'Beidou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (685, 'Diaofeng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (686, 'Néa Manolás', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (687, 'Geghanist', 'Armenia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (688, 'Qiganjidie', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (689, 'Jingzi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (690, 'Bobrov', 'Russia', '397706');
insert into kota (idKota, namaKota, negara, kodePos) values (691, 'Krajanjugosari', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (692, 'Sanxi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (693, 'Kokubunji', 'Japan', '952-0304');
insert into kota (idKota, namaKota, negara, kodePos) values (694, 'Yuanquan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (695, 'Yanahuaya', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (696, 'Mingyuedian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (697, 'Bontoc', 'Philippines', '6604');
insert into kota (idKota, namaKota, negara, kodePos) values (698, 'Yuanmen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (699, 'Mount Pearl', 'Canada', 'A1N');
insert into kota (idKota, namaKota, negara, kodePos) values (700, 'Bakalang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (701, 'Markaz Mudhaykirah', 'Yemen', null);
insert into kota (idKota, namaKota, negara, kodePos) values (702, 'Kungsbacka', 'Sweden', '434 23');
insert into kota (idKota, namaKota, negara, kodePos) values (703, 'Chechen-Aul', 'Russia', '366301');
insert into kota (idKota, namaKota, negara, kodePos) values (704, 'Malaga', 'Spain', '29071');
insert into kota (idKota, namaKota, negara, kodePos) values (705, 'Paseh', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (706, 'Sardasht', 'Iran', null);
insert into kota (idKota, namaKota, negara, kodePos) values (707, 'General Conesa', 'Argentina', '8503');
insert into kota (idKota, namaKota, negara, kodePos) values (708, 'Dapdap', 'Philippines', '5402');
insert into kota (idKota, namaKota, negara, kodePos) values (709, 'København', 'Denmark', '1532');
insert into kota (idKota, namaKota, negara, kodePos) values (710, 'Aparecida de Goiânia', 'Brazil', '74900-000');
insert into kota (idKota, namaKota, negara, kodePos) values (711, 'Marcala', 'Honduras', null);
insert into kota (idKota, namaKota, negara, kodePos) values (712, 'Sanbaishan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (713, 'Benavila', 'Portugal', '7480-205');
insert into kota (idKota, namaKota, negara, kodePos) values (714, 'Guilherand-Granges', 'France', '07509 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (715, 'Xiazhai', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (716, 'Phúc Thọ', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (717, 'Jiaqiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (718, 'Chidian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (719, 'Melenki', 'Russia', '602103');
insert into kota (idKota, namaKota, negara, kodePos) values (720, 'Wangqu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (721, 'Sainte-Marthe-sur-le-Lac', 'Canada', 'H9K');
insert into kota (idKota, namaKota, negara, kodePos) values (722, 'Kitakami', 'Japan', '956-0861');
insert into kota (idKota, namaKota, negara, kodePos) values (723, 'Qingnianlu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (724, 'Banyuresmi', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (725, 'Brandýs nad Labem-Stará Boleslav', 'Czech Republic', '250 91');
insert into kota (idKota, namaKota, negara, kodePos) values (726, 'Stockholm', 'Sweden', '112 20');
insert into kota (idKota, namaKota, negara, kodePos) values (727, 'Dazhou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (728, 'Picoto', 'Portugal', '4830-073');
insert into kota (idKota, namaKota, negara, kodePos) values (729, 'Vitória do Mearim', 'Brazil', '65350-000');
insert into kota (idKota, namaKota, negara, kodePos) values (730, 'Alasmalang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (731, 'Luo’ao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (732, 'Solna', 'Sweden', '171 05');
insert into kota (idKota, namaKota, negara, kodePos) values (733, 'Sandefjord', 'Norway', '3220');
insert into kota (idKota, namaKota, negara, kodePos) values (734, 'Montague', 'Canada', 'C0A');
insert into kota (idKota, namaKota, negara, kodePos) values (735, 'Grojec', 'Poland', '32-615');
insert into kota (idKota, namaKota, negara, kodePos) values (736, 'Jandira', 'Brazil', '06600-000');
insert into kota (idKota, namaKota, negara, kodePos) values (737, 'Tungoo', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (738, 'Zlatni Pyasatsi', 'Bulgaria', '9194');
insert into kota (idKota, namaKota, negara, kodePos) values (739, 'Zhenxi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (740, 'Santa Bárbara', 'Venezuela', null);
insert into kota (idKota, namaKota, negara, kodePos) values (741, 'Taipingchuan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (742, 'Kaavi', 'Finland', '73601');
insert into kota (idKota, namaKota, negara, kodePos) values (743, 'Laguna Salada', 'Dominican Republic', '11004');
insert into kota (idKota, namaKota, negara, kodePos) values (744, 'Suvorov', 'Russia', '301439');
insert into kota (idKota, namaKota, negara, kodePos) values (745, 'Dongmazar', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (746, 'Wonosobo', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (747, 'Syriam', 'Myanmar', null);
insert into kota (idKota, namaKota, negara, kodePos) values (748, 'Mucumpiz', 'Venezuela', null);
insert into kota (idKota, namaKota, negara, kodePos) values (749, 'Umuquena', 'Venezuela', null);
insert into kota (idKota, namaKota, negara, kodePos) values (750, 'Salt Lake City', 'United States', '84105');
insert into kota (idKota, namaKota, negara, kodePos) values (751, 'Otukpa', 'Nigeria', null);
insert into kota (idKota, namaKota, negara, kodePos) values (752, 'Malysheva', 'Russia', '624287');
insert into kota (idKota, namaKota, negara, kodePos) values (753, 'Sabtang', 'Philippines', '3904');
insert into kota (idKota, namaKota, negara, kodePos) values (754, 'Capalonga', 'Philippines', '4607');
insert into kota (idKota, namaKota, negara, kodePos) values (755, 'San Pedro', 'Bolivia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (756, 'La Jagua de Ibirico', 'Colombia', '203027');
insert into kota (idKota, namaKota, negara, kodePos) values (757, 'Dzhankoy', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (758, 'Tigbaw', 'Philippines', '1715');
insert into kota (idKota, namaKota, negara, kodePos) values (759, 'Fendou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (760, 'Hongshanyao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (761, 'Austin', 'United States', '78732');
insert into kota (idKota, namaKota, negara, kodePos) values (762, 'Angan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (763, 'Liping', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (764, 'Nanganga', 'Tanzania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (765, 'Sannikovo', 'Russia', '658059');
insert into kota (idKota, namaKota, negara, kodePos) values (766, 'Jojoima', 'Sierra Leone', null);
insert into kota (idKota, namaKota, negara, kodePos) values (767, 'Daireaux', 'Argentina', '6555');
insert into kota (idKota, namaKota, negara, kodePos) values (768, 'Privlaka', 'Croatia', '32251');
insert into kota (idKota, namaKota, negara, kodePos) values (769, 'Cuihuangkou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (770, 'Taunan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (771, 'Cajati', 'Brazil', '11950-000');
insert into kota (idKota, namaKota, negara, kodePos) values (772, 'Gurung', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (773, 'Przemków', 'Poland', '59-171');
insert into kota (idKota, namaKota, negara, kodePos) values (774, 'Moreira de Geraz do Lima', 'Portugal', '4905-266');
insert into kota (idKota, namaKota, negara, kodePos) values (775, 'Jiji', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (776, 'San Salvador de Jujuy', 'Argentina', '4600');
insert into kota (idKota, namaKota, negara, kodePos) values (777, 'Nove-Misto', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (778, 'Sioah', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (779, 'Yanhe', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (780, 'Jati', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (781, 'Novais', 'Portugal', '4765-122');
insert into kota (idKota, namaKota, negara, kodePos) values (782, 'Cabedelo', 'Brazil', '58310-000');
insert into kota (idKota, namaKota, negara, kodePos) values (783, 'Ráječko', 'Czech Republic', '679 02');
insert into kota (idKota, namaKota, negara, kodePos) values (784, 'Kawerau', 'New Zealand', '3192');
insert into kota (idKota, namaKota, negara, kodePos) values (785, 'Parchowo', 'Poland', '77-124');
insert into kota (idKota, namaKota, negara, kodePos) values (786, 'Nugas', 'Philippines', '3102');
insert into kota (idKota, namaKota, negara, kodePos) values (787, 'Xinzhou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (788, 'Vallentuna', 'Sweden', '186 53');
insert into kota (idKota, namaKota, negara, kodePos) values (789, 'Danauparis', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (790, 'Rancaseneng', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (791, 'Mainang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (792, 'Mollas', 'Albania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (793, 'Pustá Polom', 'Czech Republic', '747 69');
insert into kota (idKota, namaKota, negara, kodePos) values (794, 'Yabluniv', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (795, 'Ngerengere', 'Tanzania', null);
insert into kota (idKota, namaKota, negara, kodePos) values (796, 'Grand Forks', 'United States', '58207');
insert into kota (idKota, namaKota, negara, kodePos) values (797, 'Chatou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (798, 'Al Majd', 'Palestinian Territory', null);
insert into kota (idKota, namaKota, negara, kodePos) values (799, 'Huoxian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (800, 'Ko Pha Ngan', 'Thailand', '22110');
insert into kota (idKota, namaKota, negara, kodePos) values (801, 'Chalaco', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (802, 'Tagdanua', 'Philippines', '9320');
insert into kota (idKota, namaKota, negara, kodePos) values (803, 'Kostyantynivka', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (804, 'Pojok', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (805, 'Yoshikawa', 'Japan', '990-0711');
insert into kota (idKota, namaKota, negara, kodePos) values (806, 'Plaridel', 'Philippines', '7209');
insert into kota (idKota, namaKota, negara, kodePos) values (807, 'Taung', 'South Africa', '8609');
insert into kota (idKota, namaKota, negara, kodePos) values (808, 'Ensanche Luperón', 'Dominican Republic', '11806');
insert into kota (idKota, namaKota, negara, kodePos) values (809, 'Bojongaren', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (810, 'Middleton', 'United Kingdom', 'LE16');
insert into kota (idKota, namaKota, negara, kodePos) values (811, 'La Tuque', 'Canada', 'G9X');
insert into kota (idKota, namaKota, negara, kodePos) values (812, 'Sápes', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (813, 'Dakhla', 'Western Sahara', null);
insert into kota (idKota, namaKota, negara, kodePos) values (814, 'Huari', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (815, 'Zhengwan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (816, 'Quillo', 'Peru', null);
insert into kota (idKota, namaKota, negara, kodePos) values (817, 'Hwangju-ŭp', 'North Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (818, 'Nazran’', 'Russia', '386150');
insert into kota (idKota, namaKota, negara, kodePos) values (819, 'Gorbunki', 'Russia', '188502');
insert into kota (idKota, namaKota, negara, kodePos) values (820, 'Mlaka pri Kranju', 'Slovenia', '4212');
insert into kota (idKota, namaKota, negara, kodePos) values (821, 'São Bartolomeu', 'Portugal', '2530-700');
insert into kota (idKota, namaKota, negara, kodePos) values (822, 'Paine', 'Chile', null);
insert into kota (idKota, namaKota, negara, kodePos) values (823, 'Thị Trấn Bắc Yên', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (824, 'Huolongmen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (825, 'Emiliano Zapata', 'Mexico', '61607');
insert into kota (idKota, namaKota, negara, kodePos) values (826, 'Thị Trấn Kim Tân', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (827, 'Sekirnik', 'Macedonia', '2435');
insert into kota (idKota, namaKota, negara, kodePos) values (828, 'San Antonio Ilotenango', 'Guatemala', '14008');
insert into kota (idKota, namaKota, negara, kodePos) values (829, 'Manevychi', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (830, 'Jiang’an', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (831, 'Hernani', 'Philippines', '6804');
insert into kota (idKota, namaKota, negara, kodePos) values (832, 'Anuchino', 'Russia', '692311');
insert into kota (idKota, namaKota, negara, kodePos) values (833, 'Koktal', 'Kazakhstan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (834, 'Zuobude', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (835, 'Kholmsk', 'Russia', '188507');
insert into kota (idKota, namaKota, negara, kodePos) values (836, 'Cimanggu Girang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (837, 'Žiželice', 'Czech Republic', '438 01');
insert into kota (idKota, namaKota, negara, kodePos) values (838, 'Caracol', 'Haiti', null);
insert into kota (idKota, namaKota, negara, kodePos) values (839, 'Pansoy', 'Philippines', '6801');
insert into kota (idKota, namaKota, negara, kodePos) values (840, 'Yanmen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (841, 'Manalongon', 'Philippines', '7029');
insert into kota (idKota, namaKota, negara, kodePos) values (842, 'Arthur’s Town', 'Bahamas', null);
insert into kota (idKota, namaKota, negara, kodePos) values (843, 'Homagama', 'Sri Lanka', '10200');
insert into kota (idKota, namaKota, negara, kodePos) values (844, 'Jinqiao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (845, 'Pondokaso', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (846, 'Nabire', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (847, 'Corona', 'United States', '92883');
insert into kota (idKota, namaKota, negara, kodePos) values (848, 'Monteiro', 'Brazil', '58500-000');
insert into kota (idKota, namaKota, negara, kodePos) values (849, 'El Mirador', 'Mexico', '14449');
insert into kota (idKota, namaKota, negara, kodePos) values (850, 'Kasamatsuchō', 'Japan', '504-0968');
insert into kota (idKota, namaKota, negara, kodePos) values (851, 'Västerås', 'Sweden', '721 32');
insert into kota (idKota, namaKota, negara, kodePos) values (852, 'Wuqishan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (853, 'Liuliping', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (854, 'Strasbourg', 'France', '67073 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (855, 'Tupaciguara', 'Brazil', '38430-000');
insert into kota (idKota, namaKota, negara, kodePos) values (856, 'Jamban', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (857, 'Changgang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (858, 'Jingyao', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (859, 'Oslo', 'Norway', '0571');
insert into kota (idKota, namaKota, negara, kodePos) values (860, 'Nevel’', 'Russia', '182520');
insert into kota (idKota, namaKota, negara, kodePos) values (861, 'Mainit', 'Philippines', '8407');
insert into kota (idKota, namaKota, negara, kodePos) values (862, 'Roanne', 'France', '42335 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (863, 'Talovyy', 'Russia', '346536');
insert into kota (idKota, namaKota, negara, kodePos) values (864, 'Qili', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (865, 'Barcelona', 'Spain', '08075');
insert into kota (idKota, namaKota, negara, kodePos) values (866, 'Ágios Matthaíos', 'Greece', null);
insert into kota (idKota, namaKota, negara, kodePos) values (867, 'Lidingö', 'Sweden', '181 23');
insert into kota (idKota, namaKota, negara, kodePos) values (868, 'New Washington', 'Philippines', '5610');
insert into kota (idKota, namaKota, negara, kodePos) values (869, 'Rucheng Chengguanzhen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (870, 'Vaitogi', 'American Samoa', '96799');
insert into kota (idKota, namaKota, negara, kodePos) values (871, 'Bai’e', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (872, 'Anping', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (873, 'El Crucero', 'Nicaragua', null);
insert into kota (idKota, namaKota, negara, kodePos) values (874, 'Sundsvall', 'Sweden', '851 78');
insert into kota (idKota, namaKota, negara, kodePos) values (875, 'Tužno', 'Croatia', '42242');
insert into kota (idKota, namaKota, negara, kodePos) values (876, 'Mitú', 'Colombia', '054028');
insert into kota (idKota, namaKota, negara, kodePos) values (877, 'Kebonsari Kidul', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (878, 'Qiaozhen', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (879, 'Besah', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (880, 'Mirocin', 'Poland', '37-565');
insert into kota (idKota, namaKota, negara, kodePos) values (881, 'Vereya', 'Russia', '142633');
insert into kota (idKota, namaKota, negara, kodePos) values (882, 'Xinbu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (883, 'Pregrada', 'Croatia', '49218');
insert into kota (idKota, namaKota, negara, kodePos) values (884, 'Longbu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (885, 'Sophia Antipolis', 'France', '06905 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (886, 'Ricardo Flores Magon', 'Mexico', '93650');
insert into kota (idKota, namaKota, negara, kodePos) values (887, 'Labangka Satu', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (888, 'Ozherel’ye', 'Russia', '142920');
insert into kota (idKota, namaKota, negara, kodePos) values (889, 'Kuripan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (890, 'Pasco', 'Argentina', '5925');
insert into kota (idKota, namaKota, negara, kodePos) values (891, 'Pesnica pri Mariboru', 'Slovenia', '2211');
insert into kota (idKota, namaKota, negara, kodePos) values (892, 'Los Angeles', 'United States', '90045');
insert into kota (idKota, namaKota, negara, kodePos) values (893, 'Washington', 'United States', '20310');
insert into kota (idKota, namaKota, negara, kodePos) values (894, 'Funga', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (895, 'Lydenburg', 'South Africa', '1126');
insert into kota (idKota, namaKota, negara, kodePos) values (896, 'Baranovichi', 'Belarus', null);
insert into kota (idKota, namaKota, negara, kodePos) values (897, 'Tabuk', 'Philippines', '6010');
insert into kota (idKota, namaKota, negara, kodePos) values (898, 'Sugiharjo', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (899, 'Andong', 'South Korea', null);
insert into kota (idKota, namaKota, negara, kodePos) values (900, 'Tajinan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (901, 'Borås', 'Sweden', '507 10');
insert into kota (idKota, namaKota, negara, kodePos) values (902, 'Nagasari', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (903, 'Isiro', 'Democratic Republic of the Congo', null);
insert into kota (idKota, namaKota, negara, kodePos) values (904, 'Stockholm', 'Sweden', '113 90');
insert into kota (idKota, namaKota, negara, kodePos) values (905, 'Calibishie', 'Dominica', null);
insert into kota (idKota, namaKota, negara, kodePos) values (906, 'Madolenihm Municipality Government', 'Micronesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (907, 'San Felipe', 'Chile', null);
insert into kota (idKota, namaKota, negara, kodePos) values (908, 'Bemposta', 'Portugal', '4980-403');
insert into kota (idKota, namaKota, negara, kodePos) values (909, 'Yumaguzino', 'Russia', '453337');
insert into kota (idKota, namaKota, negara, kodePos) values (910, 'Río Blanco', 'Nicaragua', null);
insert into kota (idKota, namaKota, negara, kodePos) values (911, 'Kapotnya', 'Russia', '140093');
insert into kota (idKota, namaKota, negara, kodePos) values (912, 'Waoundé', 'Senegal', null);
insert into kota (idKota, namaKota, negara, kodePos) values (913, 'Santa Cruz del Norte', 'Cuba', null);
insert into kota (idKota, namaKota, negara, kodePos) values (914, 'Bilovods''k', 'Ukraine', null);
insert into kota (idKota, namaKota, negara, kodePos) values (915, 'Ciseureuheun', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (916, 'Boto', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (917, 'Nedakonice', 'Czech Republic', '687 38');
insert into kota (idKota, namaKota, negara, kodePos) values (918, 'Okunoya', 'Japan', '314-0116');
insert into kota (idKota, namaKota, negara, kodePos) values (919, 'Plewiska', 'Poland', '62-056');
insert into kota (idKota, namaKota, negara, kodePos) values (920, 'Al Ḩudaydah', 'Yemen', null);
insert into kota (idKota, namaKota, negara, kodePos) values (921, 'Liangzeng', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (922, 'San Felipe', 'Chile', null);
insert into kota (idKota, namaKota, negara, kodePos) values (923, 'Austin', 'United States', '78759');
insert into kota (idKota, namaKota, negara, kodePos) values (924, 'Bŭka', 'Uzbekistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (925, 'Sukhothai', 'Thailand', '75120');
insert into kota (idKota, namaKota, negara, kodePos) values (926, 'San Martin', 'Mexico', '56199');
insert into kota (idKota, namaKota, negara, kodePos) values (927, 'Tianya', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (928, 'Jiangbei', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (929, 'Somita', 'Gambia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (930, 'Kelasuri', 'Georgia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (931, 'Gio Linh', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (932, 'Shadui', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (933, 'Terong', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (934, 'Messina', 'Italy', '98135');
insert into kota (idKota, namaKota, negara, kodePos) values (935, 'Fomento', 'Cuba', null);
insert into kota (idKota, namaKota, negara, kodePos) values (936, 'El Carmen de Bolívar', 'Colombia', '132059');
insert into kota (idKota, namaKota, negara, kodePos) values (937, 'Chantilly', 'France', '60637 CEDEX');
insert into kota (idKota, namaKota, negara, kodePos) values (938, 'Huangjinjing', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (939, 'Baiyashi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (940, 'Novopodrezkovo', 'Russia', '143020');
insert into kota (idKota, namaKota, negara, kodePos) values (941, 'Ô Môn', 'Vietnam', null);
insert into kota (idKota, namaKota, negara, kodePos) values (942, 'San Patricio', 'Paraguay', null);
insert into kota (idKota, namaKota, negara, kodePos) values (943, 'Toulouse', 'France', '31044 CEDEX 9');
insert into kota (idKota, namaKota, negara, kodePos) values (944, 'Pangatikan', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (945, 'Cabreúva', 'Brazil', '13315-000');
insert into kota (idKota, namaKota, negara, kodePos) values (946, 'Zhoinda', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (947, 'Nanling', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (948, 'Tha Ruea', 'Thailand', '13130');
insert into kota (idKota, namaKota, negara, kodePos) values (949, 'Shanhou', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (950, 'Torres Novas', 'Portugal', '2350-413');
insert into kota (idKota, namaKota, negara, kodePos) values (951, 'Chekhov', 'Russia', '142308');
insert into kota (idKota, namaKota, negara, kodePos) values (952, 'Lishan', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (953, 'Ribeirão Preto', 'Brazil', '14000-000');
insert into kota (idKota, namaKota, negara, kodePos) values (954, 'Messejana', 'Portugal', '7600-314');
insert into kota (idKota, namaKota, negara, kodePos) values (955, 'Belo Oriente', 'Brazil', '35195-000');
insert into kota (idKota, namaKota, negara, kodePos) values (956, 'Ketapang', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (957, 'Jandira', 'Brazil', '06600-000');
insert into kota (idKota, namaKota, negara, kodePos) values (958, 'Nancang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (959, 'Le Mans', 'France', '72091 CEDEX 9');
insert into kota (idKota, namaKota, negara, kodePos) values (960, 'Bahui', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (961, 'Yashalta', 'Russia', '359025');
insert into kota (idKota, namaKota, negara, kodePos) values (962, 'Xiyang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (963, 'Huashu', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (964, 'Kashirskoye', 'Russia', '396350');
insert into kota (idKota, namaKota, negara, kodePos) values (965, 'Gustavsberg', 'Sweden', '134 40');
insert into kota (idKota, namaKota, negara, kodePos) values (966, 'Abay', 'Kazakhstan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (967, 'Ganchazi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (968, 'Chadiza', 'Zambia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (969, 'Zbůch', 'Czech Republic', '330 22');
insert into kota (idKota, namaKota, negara, kodePos) values (970, 'El Calvario', 'Mexico', '68213');
insert into kota (idKota, namaKota, negara, kodePos) values (971, 'Monte Caseros', 'Argentina', '3220');
insert into kota (idKota, namaKota, negara, kodePos) values (972, 'Okakarara', 'Namibia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (973, 'Novyy Urengoy', 'Russia', '629309');
insert into kota (idKota, namaKota, negara, kodePos) values (974, 'Cinyasag', 'Indonesia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (975, 'Kiten', 'Bulgaria', '9243');
insert into kota (idKota, namaKota, negara, kodePos) values (976, 'Široki Brijeg', 'Bosnia and Herzegovina', null);
insert into kota (idKota, namaKota, negara, kodePos) values (977, 'Kol’chugino', 'Russia', '601787');
insert into kota (idKota, namaKota, negara, kodePos) values (978, 'Fonte', 'Portugal', '4615-099');
insert into kota (idKota, namaKota, negara, kodePos) values (979, 'Goryachevodskiy', 'Russia', '357560');
insert into kota (idKota, namaKota, negara, kodePos) values (980, 'Marseille', 'France', '13269 CEDEX 08');
insert into kota (idKota, namaKota, negara, kodePos) values (981, 'Loma Alta', 'Honduras', null);
insert into kota (idKota, namaKota, negara, kodePos) values (982, 'Merida', 'Philippines', '6540');
insert into kota (idKota, namaKota, negara, kodePos) values (983, 'Không', 'Laos', null);
insert into kota (idKota, namaKota, negara, kodePos) values (984, 'Narita', 'Japan', '993-0075');
insert into kota (idKota, namaKota, negara, kodePos) values (985, 'Shixian', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (986, 'Gorno Orizari', 'Macedonia', '1408');
insert into kota (idKota, namaKota, negara, kodePos) values (987, 'Kuytun', 'Russia', '665302');
insert into kota (idKota, namaKota, negara, kodePos) values (988, 'Łeba', 'Poland', '84-360');
insert into kota (idKota, namaKota, negara, kodePos) values (989, 'Quesada', 'Guatemala', '22017');
insert into kota (idKota, namaKota, negara, kodePos) values (990, 'Omaruru', 'Namibia', null);
insert into kota (idKota, namaKota, negara, kodePos) values (991, 'Sandaohezi', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (992, 'Dū Laīnah', 'Afghanistan', null);
insert into kota (idKota, namaKota, negara, kodePos) values (993, 'Água de Pau', 'Portugal', '9560-205');
insert into kota (idKota, namaKota, negara, kodePos) values (994, 'Caohezhang', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (995, 'Aveiras de Cima', 'Portugal', '2050-065');
insert into kota (idKota, namaKota, negara, kodePos) values (996, 'Bei’an', 'China', null);
insert into kota (idKota, namaKota, negara, kodePos) values (997, 'Soanindrariny', 'Madagascar', null);
insert into kota (idKota, namaKota, negara, kodePos) values (998, 'Vereshchagino', 'Russia', '303642');
insert into kota (idKota, namaKota, negara, kodePos) values (999, 'Nowy Staw', 'Poland', '82-230');
insert into kota (idKota, namaKota, negara, kodePos) values (1000, 'Ugbokpo', 'Nigeria', null);
